import { Product, Coupon, MonitoredItem, AppNotification } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-ps5-slim',
    name: 'Console PlayStation 5 Slim Edição Digital 1TB',
    brand: 'Sony',
    model: 'CFI-2014B',
    ean: '0711719572428',
    category: 'Games & Consoles',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80',
    description: 'Console PlayStation 5 Slim em design compacto com SSD ultrarrápido de 1TB, suporte a resposta tátil e gatilhos adaptáveis.',
    currentLowestPrice: 3299.00,
    historicalLowestPrice: 3099.00,
    historicalHighestPrice: 3999.00,
    targetPrice: 3200.00,
    isMonitored: true,
    offers: [
      {
        id: 'off-1',
        productId: 'prod-ps5-slim',
        storeName: 'KaBuM!',
        price: 3299.00,
        originalPrice: 3799.00,
        pixDiscountPrice: 3134.05,
        installmentText: '10x de R$ 329,90 sem juros',
        shippingPrice: 19.90,
        deliveryDays: 2,
        rating: 4.8,
        reviewCount: 1420,
        isIdentical: true,
        productUrl: 'https://www.kabum.com.br',
        inStock: true,
        couponCode: 'KABUM100',
        couponDiscount: 'R$ 100 OFF',
        lastUpdated: 'Hoje, 10:15'
      },
      {
        id: 'off-2',
        productId: 'prod-ps5-slim',
        storeName: 'Amazon Brasil',
        price: 3349.00,
        originalPrice: 3799.00,
        pixDiscountPrice: 3349.00,
        installmentText: '10x de R$ 334,90 sem juros',
        shippingPrice: 0.00, // Frete Grátis Prime
        deliveryDays: 1,
        rating: 4.9,
        reviewCount: 3850,
        isIdentical: true,
        productUrl: 'https://www.amazon.com.br',
        inStock: true,
        couponCode: 'PRIMEGAMES',
        couponDiscount: 'Frete Grátis Prime',
        lastUpdated: 'Hoje, 09:30'
      },
      {
        id: 'off-3',
        productId: 'prod-ps5-slim',
        storeName: 'Magazine Luiza',
        price: 3419.10,
        originalPrice: 3799.00,
        pixDiscountPrice: 3248.14,
        installmentText: '10x de R$ 341,91 sem juros',
        shippingPrice: 14.90,
        deliveryDays: 3,
        rating: 4.7,
        reviewCount: 940,
        isIdentical: true,
        productUrl: 'https://www.magazineluiza.com.br',
        inStock: true,
        lastUpdated: 'Ontem, 18:20'
      },
      {
        id: 'off-4',
        productId: 'prod-ps5-slim',
        storeName: 'Mercado Livre',
        price: 3489.00,
        originalPrice: 3899.00,
        pixDiscountPrice: 3419.00,
        installmentText: '12x de R$ 290,75',
        shippingPrice: 0.00,
        deliveryDays: 1,
        rating: 4.8,
        reviewCount: 2100,
        isIdentical: true,
        productUrl: 'https://www.mercadolivre.com.br',
        inStock: true,
        couponCode: 'GANHE50',
        couponDiscount: 'R$ 50 OFF',
        lastUpdated: 'Hoje, 08:00'
      },
      {
        id: 'off-5',
        productId: 'prod-ps5-slim',
        storeName: 'Fast Shop',
        price: 3599.00,
        originalPrice: 3999.00,
        pixDiscountPrice: 3399.00,
        installmentText: '10x de R$ 359,90 sem juros',
        shippingPrice: 29.90,
        deliveryDays: 2,
        rating: 4.6,
        reviewCount: 420,
        isIdentical: false, // Pacote com jogo extra
        productUrl: 'https://www.fastshop.com.br',
        inStock: true,
        lastUpdated: 'Hoje, 07:00'
      }
    ],
    priceHistory: [
      { date: '08/05', price: 3799, storeName: 'KaBuM!' },
      { date: '22/05', price: 3650, storeName: 'Amazon Brasil' },
      { date: '05/06', price: 3599, storeName: 'KaBuM!' },
      { date: '19/06', price: 3499, storeName: 'Magazine Luiza' },
      { date: '03/07', price: 3399, storeName: 'KaBuM!' },
      { date: '17/07', price: 3099, storeName: 'Amazon Brasil' },
      { date: '01/08', price: 3350, storeName: 'Mercado Livre' },
      { date: '06/08', price: 3299, storeName: 'KaBuM!' },
    ]
  },
  {
    id: 'prod-iphone16-pro',
    name: 'Smartphone Apple iPhone 16 Pro 256GB Titanio Natural',
    brand: 'Apple',
    model: 'MYNN3BR/A',
    ean: '0195949051421',
    category: 'Smartphones & Celulares',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
    description: 'iPhone 16 Pro com estrutura em titânio, tela Super Retina XDR de 6.3 polegadas, chip A18 Pro e controle de câmera avançado.',
    currentLowestPrice: 8499.00,
    historicalLowestPrice: 8199.00,
    historicalHighestPrice: 9499.00,
    targetPrice: 8200.00,
    isMonitored: true,
    offers: [
      {
        id: 'off-ip1',
        productId: 'prod-iphone16-pro',
        storeName: 'Amazon Brasil',
        price: 8499.00,
        originalPrice: 9499.00,
        pixDiscountPrice: 7904.07,
        installmentText: '12x de R$ 708,25 sem juros',
        shippingPrice: 0.00,
        deliveryDays: 1,
        rating: 4.9,
        reviewCount: 530,
        isIdentical: true,
        productUrl: 'https://www.amazon.com.br',
        inStock: true,
        couponCode: 'APPLE10',
        couponDiscount: '10% Pix Extra',
        lastUpdated: 'Hoje, 11:00'
      },
      {
        id: 'off-ip2',
        productId: 'prod-iphone16-pro',
        storeName: 'Fast Shop',
        price: 8599.00,
        originalPrice: 9499.00,
        pixDiscountPrice: 7999.00,
        installmentText: '10x de R$ 859,90 sem juros',
        shippingPrice: 19.90,
        deliveryDays: 1,
        rating: 4.8,
        reviewCount: 310,
        isIdentical: true,
        productUrl: 'https://www.fastshop.com.br',
        inStock: true,
        lastUpdated: 'Hoje, 09:45'
      },
      {
        id: 'off-ip3',
        productId: 'prod-iphone16-pro',
        storeName: 'Mercado Livre',
        price: 8690.00,
        originalPrice: 9499.00,
        pixDiscountPrice: 8500.00,
        installmentText: '12x de R$ 724,16',
        shippingPrice: 0.00,
        deliveryDays: 2,
        rating: 4.7,
        reviewCount: 890,
        isIdentical: true,
        productUrl: 'https://www.mercadolivre.com.br',
        inStock: true,
        lastUpdated: 'Ontem, 20:10'
      }
    ],
    priceHistory: [
      { date: '08/05', price: 9499, storeName: 'Fast Shop' },
      { date: '22/05', price: 9299, storeName: 'Amazon Brasil' },
      { date: '05/06', price: 8999, storeName: 'Magazine Luiza' },
      { date: '19/06', price: 8799, storeName: 'Fast Shop' },
      { date: '03/07', price: 8599, storeName: 'Amazon Brasil' },
      { date: '17/07', price: 8199, storeName: 'Mercado Livre' },
      { date: '06/08', price: 8499, storeName: 'Amazon Brasil' },
    ]
  },
  {
    id: 'prod-airfryer-mondial',
    name: 'Fritadeira Elétrica Air Fryer Mondial Grand Family 4L Inox AFN-40-BI',
    brand: 'Mondial',
    model: 'AFN-40-BI',
    ean: '7898490165421',
    category: 'Eletrodomésticos',
    image: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=600&q=80',
    description: 'Air Fryer com 4 Litros de capacidade, antiaderente Duraflon, controle de temperatura até 200°C e timer de 60 minutos.',
    currentLowestPrice: 289.90,
    historicalLowestPrice: 249.00,
    historicalHighestPrice: 399.00,
    targetPrice: 260.00,
    isMonitored: false,
    offers: [
      {
        id: 'off-af1',
        productId: 'prod-airfryer-mondial',
        storeName: 'Magazine Luiza',
        price: 289.90,
        originalPrice: 399.00,
        pixDiscountPrice: 275.41,
        installmentText: '5x de R$ 57,98 sem juros',
        shippingPrice: 12.00,
        deliveryDays: 2,
        rating: 4.8,
        reviewCount: 4500,
        isIdentical: true,
        productUrl: 'https://www.magazineluiza.com.br',
        inStock: true,
        couponCode: 'MAGA10',
        couponDiscount: 'R$ 10 OFF',
        lastUpdated: 'Hoje, 08:30'
      },
      {
        id: 'off-af2',
        productId: 'prod-airfryer-mondial',
        storeName: 'Amazon Brasil',
        price: 299.00,
        originalPrice: 389.00,
        pixDiscountPrice: 299.00,
        installmentText: '6x de R$ 49,83 sem juros',
        shippingPrice: 0.00,
        deliveryDays: 1,
        rating: 4.9,
        reviewCount: 8200,
        isIdentical: true,
        productUrl: 'https://www.amazon.com.br',
        inStock: true,
        lastUpdated: 'Hoje, 09:10'
      },
      {
        id: 'off-af3',
        productId: 'prod-airfryer-mondial',
        storeName: 'Shopee',
        price: 279.00,
        originalPrice: 350.00,
        pixDiscountPrice: 279.00,
        installmentText: '3x de R$ 93,00',
        shippingPrice: 15.00,
        deliveryDays: 5,
        rating: 4.6,
        reviewCount: 1200,
        isIdentical: false, // Modelo 3.5L similar
        productUrl: 'https://shopee.com.br',
        inStock: true,
        lastUpdated: 'Ontem, 16:00'
      }
    ],
    priceHistory: [
      { date: '08/05', price: 389, storeName: 'Magazine Luiza' },
      { date: '22/05', price: 349, storeName: 'Amazon Brasil' },
      { date: '05/06', price: 319, storeName: 'Shopee' },
      { date: '19/06', price: 299, storeName: 'Magazine Luiza' },
      { date: '03/07', price: 249, storeName: 'Amazon Brasil' },
      { date: '17/07', price: 299, storeName: 'Amazon Brasil' },
      { date: '06/08', price: 289.9, storeName: 'Magazine Luiza' },
    ]
  },
  {
    id: 'prod-tv-lg-oled',
    name: 'Smart TV 55" 4K LG OLED EVO C3 120Hz Dolby Vision G-Sync',
    brand: 'LG',
    model: 'OLED55C3PSA',
    ean: '7893299943210',
    category: 'TVs & Áudio',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
    description: 'Smart TV OLED C3 com processador α9 Gen6 AI, 4 portas HDMI 2.1 para games 4K 120Hz e som imersivo Dolby Atmos.',
    currentLowestPrice: 5199.00,
    historicalLowestPrice: 4899.00,
    historicalHighestPrice: 6899.00,
    targetPrice: 5000.00,
    isMonitored: true,
    offers: [
      {
        id: 'off-tv1',
        productId: 'prod-tv-lg-oled',
        storeName: 'Fast Shop',
        price: 5199.00,
        originalPrice: 6899.00,
        pixDiscountPrice: 4887.06,
        installmentText: '10x de R$ 519,90 sem juros',
        shippingPrice: 49.00,
        deliveryDays: 3,
        rating: 4.9,
        reviewCount: 620,
        isIdentical: true,
        productUrl: 'https://www.fastshop.com.br',
        inStock: true,
        couponCode: 'FASTTV5',
        couponDiscount: '5% OFF extra',
        lastUpdated: 'Hoje, 07:12'
      },
      {
        id: 'off-tv2',
        productId: 'prod-tv-lg-oled',
        storeName: 'KaBuM!',
        price: 5299.00,
        originalPrice: 6899.00,
        pixDiscountPrice: 5034.05,
        installmentText: '10x de R$ 529,90 sem juros',
        shippingPrice: 35.00,
        deliveryDays: 4,
        rating: 4.8,
        reviewCount: 310,
        isIdentical: true,
        productUrl: 'https://www.kabum.com.br',
        inStock: true,
        lastUpdated: 'Ontem, 21:00'
      }
    ],
    priceHistory: [
      { date: '08/05', price: 6899, storeName: 'Fast Shop' },
      { date: '22/05', price: 6299, storeName: 'KaBuM!' },
      { date: '05/06', price: 5899, storeName: 'Fast Shop' },
      { date: '19/06', price: 5499, storeName: 'Magazine Luiza' },
      { date: '03/07', price: 4899, storeName: 'Fast Shop' },
      { date: '17/07', price: 5399, storeName: 'Amazon Brasil' },
      { date: '06/08', price: 5199, storeName: 'Fast Shop' },
    ]
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    storeName: 'KaBuM!',
    code: 'KABUM100',
    discountText: 'R$ 100 OFF',
    discountValue: 'R$ 100',
    minPurchase: 1000,
    category: 'Games & Hardware',
    expiryDate: '31/08/2026',
    verified: true,
    terms: 'Válido para compras acima de R$ 1.000 em produtos vendidos e entregues pela KaBuM!'
  },
  {
    id: 'coup-2',
    storeName: 'Amazon Brasil',
    code: 'PRIMEGAMES',
    discountText: 'Frete Grátis Prime',
    discountValue: 'Frete Grátis',
    minPurchase: 0,
    category: 'Games',
    expiryDate: '15/09/2026',
    verified: true,
    terms: 'Válido para assinantes Amazon Prime em itens com selo Prime.'
  },
  {
    id: 'coup-3',
    storeName: 'Magazine Luiza',
    code: 'MAGA10',
    discountText: '10% OFF em Eletrodomésticos',
    discountValue: '10%',
    minPurchase: 200,
    category: 'Eletrodomésticos',
    expiryDate: '20/08/2026',
    verified: true,
    terms: 'Desconto máximo de R$ 150. Aplicável no aplicativo Magalu.'
  },
  {
    id: 'coup-4',
    storeName: 'Fast Shop',
    code: 'FASTTV5',
    discountText: '5% OFF extra no Pix',
    discountValue: '5%',
    minPurchase: 2000,
    category: 'TVs & Áudio',
    expiryDate: '30/08/2026',
    verified: true,
    terms: 'Cumulativo com desconto de pagamento à vista por PIX.'
  },
  {
    id: 'coup-5',
    storeName: 'Mercado Livre',
    code: 'GANHE50',
    discountText: 'R$ 50 OFF em Eletrônicos',
    discountValue: 'R$ 50',
    minPurchase: 500,
    category: 'Eletrônicos',
    expiryDate: '10/08/2026',
    verified: true,
    terms: 'Válido em produtos selecionados com frete Full.'
  }
];

export const INITIAL_MONITORED: MonitoredItem[] = [
  {
    id: 'mon-1',
    productId: 'prod-ps5-slim',
    productTitle: 'Console PlayStation 5 Slim Edição Digital 1TB',
    productImage: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80',
    currentLowestPrice: 3299.00,
    targetPrice: 3200.00,
    collection: 'Games & Tech',
    alertFrequency: 'immediate',
    notificationsEnabled: true,
    createdAt: '01/08/2026'
  },
  {
    id: 'mon-2',
    productId: 'prod-iphone16-pro',
    productTitle: 'Smartphone Apple iPhone 16 Pro 256GB Titanio',
    productImage: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
    currentLowestPrice: 8499.00,
    targetPrice: 8200.00,
    collection: 'Games & Tech',
    alertFrequency: 'daily',
    notificationsEnabled: true,
    createdAt: '03/08/2026'
  },
  {
    id: 'mon-3',
    productId: 'prod-tv-lg-oled',
    productTitle: 'Smart TV 55" 4K LG OLED EVO C3 120Hz',
    productImage: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
    currentLowestPrice: 5199.00,
    targetPrice: 5000.00,
    collection: 'Casa Nova',
    alertFrequency: 'immediate',
    notificationsEnabled: true,
    createdAt: '05/08/2026'
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: '📉 Queda de Preço Detectada!',
    message: 'PlayStation 5 Slim baixou para R$ 3.299 na KaBuM! (está apenas R$ 99 acima da sua meta de R$ 3.200)',
    date: 'Hoje, 10:15',
    type: 'price_drop',
    productId: 'prod-ps5-slim',
    read: false
  },
  {
    id: 'notif-2',
    title: '🎟️ Novo Cupom Verificado',
    message: 'Novo cupom FASTTV5 concedendo 5% OFF extra em TVs na Fast Shop.',
    date: 'Hoje, 07:15',
    type: 'new_coupon',
    productId: 'prod-tv-lg-oled',
    read: false
  },
  {
    id: 'notif-3',
    title: '🔥 Menor Preço dos últimos 30 dias!',
    message: 'Smart TV LG OLED 55 C3 atingiu R$ 4.887,06 no PIX na Fast Shop.',
    date: 'Ontem',
    type: 'price_drop',
    productId: 'prod-tv-lg-oled',
    read: true
  }
];
